[package]

name = "uo-data-viewer"
version = "0.0.1"
authors = ["Tony Aldridge <tony@angry-lawyer.com>"]

[dependencies]
image = "0.18"

[dependencies.sdl2]
version = "0.31.0"
features = ["ttf"]

[dependencies.uo-rust-libs]
git = "https://github.com/AngryLawyer/uo-rust-libs.git"

[dependencies.sdl2-engine-helpers]
git = "https://github.com/AngryLawyer/rust-sdl2-engine-helpers.git"
